controllers/MenuController.php
<?php

namespace app\controllers;

use app\models\MenuItem;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class MenuController extends Controller
{
    /** {@inheritdoc} */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @param MenuItem $menuItem
     * @return array
     */
    private function _generateSubmenu($menuItem) {
        $item = [
            'id' => $menuItem->id,
            'title' => $menuItem->title,
            'link' => $menuItem->link,
            'submenu' => [],
        ];

        $children = $menuItem->getChildren()->all();
        foreach ($children as $submenuItem) {
            $submenu = $this->_generateSubmenu($submenuItem);
            $item['submenu'][$submenu['id']] = $submenu;
        }

        return $item;
    }

    /** @return array */
    private function _generateMenu() {
        $menu = [];
        $rootItems = MenuItem::find()->root()->all();
        foreach ($rootItems as $rootItem) {
            $submenu = $this->_generateSubmenu($rootItem);
            $menu[$submenu['id']] = $submenu;
        }

        return $menu;
    }

    /**
     * @param array $menuArray
     * @param integer $level Level of nesting (root is 0)
     * @return array Array consisting of one item whenever no children, or more if there are children
     */
    private function _convertMenuForDropdown($menuArray, $level) {
        $result = [
            '' => '(root)',
        ];
        foreach ($menuArray as $menuItem) {
            $result[$menuItem['id']] = str_repeat('-', $level) . ' ' . $menuItem['title'];
            $result += $this->_convertMenuForDropdown($menuItem['submenu'], $level + 1);
        }
        return $result;
    }

    public function actionIndex() {
        $menu = $this->_generateMenu();

        return $this->render('index', ['menu' => $menu]);
    }

    public function actionCreate($parentID = null) {
        $model = new MenuItem();
        if (isset($parentID)) {
            $model->parent_id = $parentID;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'menu' => $this->_convertMenuForDropdown($this->_generateMenu(), 0),
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        $menu = $this->_convertMenuForDropdown($this->_generateMenu(), 0);
        $menu[$id] .= " (you're editing me - can't be child of myself)";

        return $this->render('update', [
            'model' => $model,
            'menu' => $menu,
        ]);
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MenuItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MenuItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = MenuItem::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested menu item does not exist.');
    }
}

views/menu/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MenuItem */
/* @var $form ActiveForm */
/* @var $menu array */
?>
<div class="menu-_form">

    <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'title') ?>
        <?= $form->field($model, 'link') ?>
        <?= $form->field($model, 'parent_id')->dropDownList($menu, [
            'options' => [
                $model->id => [
                    'disabled' => true,
                ],
            ],
        ]) ?>
    
        <div class="form-group">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- menu-_form -->

views/menu/_submenu.php
<?php
use yii\helpers\Html;
use richardfan\widget\JSRegister;
/* @var $this yii\web\View */
/* @var $menu array */
?>

<ul>
    <?php foreach ($menu as $item): ?>
    <li>
        <?= Html::a($item['title'], $item['link']) ?>
        (ID: <?=$item['id']?>)
        <a class="btn btn-info" href="<?=Yii::$app->urlManager->createUrl(['menu/update', 'id' => $item['id']])?>">Edit</a>
        <a class="btn btn-success" href="<?=Yii::$app->urlManager->createUrl(['menu/create', 'parentID' => $item['id']])?>">Add subitem</a>
        <?= Html::beginForm(['menu/delete', 'id' => $item['id']], 'post', ['style' => 'display: inline-block;', 'class' => 'frmDelete']) ?>
            <?= Html::submitButton('Delete', ['class' => 'btn btn-danger']) ?>
        <?= Html::endForm() ?>

        <?php if (!empty($item['submenu'])) {
            echo $this->render('_submenu', ['menu' => $item['submenu']]);
        } ?>
    </li>
    <?php endforeach; ?>

    <?php JSRegister::begin() ?>
    <script>
        $(document).on('submit', 'form.frmDelete', function() {
            return confirm('Are you sure to delete?');
        });
    </script>
    <?php JSRegister::end() ?>
</ul>

views/menu/create.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\MenuItem */
/* @var $menu array */

$this->title = 'Create menu item';
?>

<h1><?=$this->title?></h1>

<?=$this->render('_form', [
    'model' => $model,
    'menu' => $menu,
])?>

views/menu/index.php
<?php

/* @var $this yii\web\View */
/* @var $menu array */

$this->title = 'Menu';
?>

<h1>Menu</h1>

<a class="btn btn-success" href="<?=Yii::$app->urlManager->createUrl(['/menu/create'])?>">Add root item</a>
<?php echo $this->render('_submenu', ['menu' => $menu]); ?>

views/menu/update.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\MenuItem */
/* @var $menu array */

$this->title = 'Edit menu item';
?>

<h1><?=$this->title?></h1>

<?=$this->render('_form', [
    'model' => $model,
    'menu' => $menu,
])?>